(defpackage #:mcp-protocol
  (:use #:cl)
  (:export
   #:+mcp-protocol-version+
   #:+mcp-legacy-protocol-version+
   #:+mcp-error-unsupported-protocol-version+
   #:*supported-protocol-versions*
   #:mcp-error
   #:mcp-error-message
   #:mcp-error-code
   #:mcp-error-data
   #:mcp-peer
   #:mcp-server
   #:mcp-client
   #:mcp-tool
   #:mcp-resource
   #:mcp-prompt
   #:mcp-backend
   #:mcp-peer-name
   #:mcp-peer-version
   #:mcp-server-protocol-version
   #:mcp-server-tools
   #:mcp-server-resources
   #:mcp-server-prompts
   #:mcp-server-instructions
   #:mcp-client-transport
   #:mcp-client-era
   #:mcp-client-protocol-version
   #:mcp-client-client-capabilities
   #:mcp-client-server-info
   #:mcp-client-server-capabilities
   #:mcp-client-instructions
   #:make-mcp-tool
   #:make-mcp-resource
   #:make-mcp-prompt
   #:mcp-tool-name
   #:mcp-tool-description
   #:mcp-tool-input-schema
   #:mcp-tool-handler
   #:mcp-resource-uri
   #:mcp-resource-name
   #:mcp-resource-description
   #:mcp-resource-mime-type
   #:mcp-resource-handler
   #:mcp-prompt-name
   #:mcp-prompt-description
   #:mcp-prompt-arguments
   #:mcp-prompt-handler
   #:register-tool
   #:register-resource
   #:register-prompt
   #:mcp-discover
   #:mcp-initialize
   #:mcp-ping
   #:mcp-cancel
   #:list-tools
   #:call-tool
   #:list-resources
   #:read-resource
   #:list-prompts
   #:get-prompt
   #:dispatch-mcp-method
   #:serve-mcp
   #:make-text-content
   #:tool-result
   #:json-object
   #:param
   #:*mcp-backend*
   #:mcp-connect
   #:mcp-serve
   #:backend-mcp-connect
   #:backend-mcp-serve
   #:use-mcp-backend)
  (:documentation
   "MCP dual-era protocol: modern 2026-07-28 (stateless _meta + server/discover)
    and legacy 2025-11-25 (initialize handshake). JSON-RPC via rpc-protocol."))
